# Server configuration

include = ["net.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 512

# Package settings
[packages]
bash = {}
ca-certificates = {}
contain = {}
coreutils = {}
curl = {}
diffutils = {}
extrautils = {}
findutils = {}
# git = {} - needs conversion to recipe.toml due to dependencies
installer = {}
ion = {}
kibi = {}
netdb = {}
pkgutils = {}
redoxfs = {}
resist = {}
userutils = {}

[[files]]
path = "/usr/lib/init.d/30_console"
data = """
inputd -A 2
getty 2
getty /scheme/debug/no-preserve -J
"""
