# The Redox build server configuration

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
base = {}
base-initfs = {}
bootloader = {}
ca-certificates = {}
#contain = {} # redox_syscall 0.4 not working on riscv64gc?
coreutils = {}
dash = {}
diffutils = {}
drivers = {}
extrautils = {}
findutils = {}
hicolor-icon-theme = {}
installer = {}
#installer-gui = {} # redox_syscall 0.4 not working on riscv64gc?
ion = {}
kernel = {}
#nano = {} # error compiling ncurses
netdb = {}
#netsurf = {} # error compiling nghttp2
netutils = {}
orbdata = {}
orbital = {}
orbterm = {}
orbutils = {}
pkgutils = {}
redoxfs = {}
relibc = {}
resist = {}
smith = {}
userutils = {}
uutils = {}
#vim = {} # error compiling ncurses

#TODO: Add more packages
