# The Redox build server configuration

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
base = {}
base-initfs = {}
bootloader = {}
ca-certificates = {}
contain = {}
coreutils = {}
dash = {}
diffutils = {}
drivers = {}
extrautils = {}
findutils = {}
hicolor-icon-theme = {}
installer = {}
installer-gui = {}
ion = {}
kernel = {}
nano = {}
netdb = {}
netsurf = {}
netutils = {}
orbdata = {}
orbital = {}
orbterm = {}
orbutils = {}
pkgutils = {}
redoxfs = {}
relibc = {}
resist = {}
smith = {}
userutils = {}
uutils = {}
vim = {}

#TODO: Add more packages
